### ISSUE TITLE
Doubledash for long options

### ISSUE THREAD

**Issue by rockandska** [simulot/aspiratv#41]
It feels really weird to have only one dash for long options `-destination` instead of `--destination`.
[Usually](https://unix.stackexchange.com/a/21854), short options (-d) have one dash when long options (--destination) have two.

Additionally, using [docopt](https://github.com/docopt/docopt.go) for writing `usage:` section and automatically generate parser is a nice module when writing command-line tools and is ported in various [language](https://github.com/docopt)

Regards,

**Comment by simulot** [comment]
Ho Rockandska,

Indeed. Currently, I'm using go default library for parsing options which doesn't implement -- style.
However, this makes sense to be complaint with habits.
It's on my list.
