### ISSUE TITLE
destination path not valid in different use case

### ISSUE THREAD

**Issue by rockandska** [simulot/aspiratv#42]
Valid :
```
$ aspiratv -provider artetv -destination /tmp download "dos au mur"
$ aspiratv -provider artetv -destination ~/Downloads download "dos au mur"
```

Not valid but should be valid :
```
$ aspiratv -provider artetv -destination ~/Downloads/ download "dos au mur"
$ aspiratv -provider artetv -destination /tmp/ download "dos au mur"
$ aspiratv -provider artetv -destination ./ download "dos au mur"
$ aspiratv -provider artetv -destination . download "dos au mur"
```

**Comment by simulot** [comment]
Hi,

This is expected. I would like to prevent path traversal vulnerability. The rule I have implemented is that given path must be absolute to avoid something like ../../../../../../../../etc as destination.

However, /tmp/ should work as this is an absolute path. I'll fix it. 

But we can discuss about what should be implemented.

**Comment by rockandska** [comment]
> I would like to prevent path traversal vulnerability

With a website I could understand, but can't see how it could be applied here. There are no privileges escalation with aspiratv so a user could not write outside its home but maybe I'm missing something :)

> However, /tmp/ should work as this is an absolute path. I'll fix it.

Could be handy to have an error message with the reason when a path is not valid to yours rules or not writable because i didn't get what i was doing wrong at first glance ^^

**Comment by simulot** [comment]
I have removed the path validation.
