### ISSUE TITLE
Problem provider FranceTV

### ISSUE THREAD

**Issue by ludo77** [simulot/aspiratv#52]
Hello,
I have a problem, I discovered aspiratv.
I wanted to use this command:
`./aspiratv --provider=francetv --destination=$HOME/Videos/DL download "Maman a tort"`
But I end up with this error:
`aspiratv: 0.11.2, commit cf7c100, built at 2020-05-07T13:39:03Z
 [----------]     0/  0      Pulling francetv
2020/06/06 09:44:06 [ERROR] [francetv] Can't call algolia API: Can't get response to "POST" :"403 Forbidden"
Body:
 [----------] completed      Pulling francetv
`
as well as for all francetv programs
Please help me
Thanks

**Comment by simulot** [comment]
Hi Ludo77
Thanks for the report. I'll check this asap. 
Merci
Simulot

**Comment by simulot** [comment]
Well, FRANCE TV has changed the way to perform search on the site.
I'm working on using a new method.

**Comment by simulot** [comment]
@ludo77 Please check latest release.
