### ISSUE TITLE
How to modify and compile?

### ISSUE THREAD

**Issue by julll190** [simulot/aspiratv#54]
Hello !

Your software "aspiratv" is interesting me a lot, and I would like to personalize it a little bit.
But I need your help to have a look and to understand what you did (I am a newbie in Go programming :D):
- I already installed go1.14.4, made the test "hello world", compiled it, and my installation works well.
- Which software do you advise me (Windows user) to modify the code?
- Which file is launched at first? Is it "cmd\aspiratv\main.go" ?
- Which command do you type in order to compile your code?

Thank you very much for help!
Ju

**Comment by simulot** [comment]
Hi @julll190 

Here are tools you can use for starting with Go on windows:
- Go itself
- Visual Studio Code as IDE. (https://code.visualstudio.com/download)
- Go extension for VSCODE (https://code.visualstudio.com/docs/languages/go)

the command aspiratv is not placed at top level, but in cmd/aspiratv folder.  So move to this place, and type:
```
go buld 
```
You will get an executable.

Have fun with this.
++ Simulot

**Comment by ice-walker** [comment]
Hello,
Congratulation for your great software!
Is there a way to compile your code from the command line (using GOlang on UBUNTU)?
Thanks, Ice

**Comment by julll190** [comment]
> Hi @julll190
> 
> Here are tools you can use for starting with Go on windows:
> 
> * Go itself
> * Visual Studio Code as IDE. (https://code.visualstudio.com/download)
> * Go extension for VSCODE (https://code.visualstudio.com/docs/languages/go)
> 
> the command aspiratv is not placed at top level, but in cmd/aspiratv folder. So move to this place, and type:
> 
> ```
> go buld 
> ```
> 
> You will get an executable.
> 
> Have fun with this.
> ++ Simulot

Thank you for answer, I installed everything and it's OK now.
I just need to find some time to study your code ;), I didn't thought it would be so long and complicated.

**Comment by ice-walker** [comment]
> Hello,
> Congratulation for your great software!
> Is there a way to compile your code from the command line (using GOlang on UBUNTU)?
> Thanks, Ice

Compile fine under Linux too :) took me a while to see, one really must be in [cmd/aspiratv] before calling the [go build] command :) let's have a look
