### ISSUE TITLE
francetv "Irak, destruction d'une nation" 

### ISSUE THREAD

**Issue by yves2** [simulot/aspiratv#60]
je n'arrive pas à la télécharger avec la commande :
aspiratv --provider=francetv --destination ~/Videos/DL download "Irak, destruction d’une nation"
j'ai essayél'exemple  "la minute vieille"   ...parfait

j'ai essayé un config.json en recopiant le code du readme.md
résultat :
aspiratv$ ./aspiratv --config ./config.json
aspiratv: 0.12.0, commit 5edd7da, built at 2020-06-07T16:42:12Z
2021/02/01 19:45:20 [FATAL] [Initialize] Can't decode configuration file: invalid character '}' looking for beginning of object key string
malgré plusieurs tentatives je suis incapable de trouver l'erreur

**Comment by simulot** [comment]
Le fichier config.json n'est pas correctement contruit. Mais il n'est pas requis pour télécharger directement un fichier.
Vous pouvez le supprimer.

Après cela les épisodes ne sont pas trouvés.
Je regarde ça

**Comment by yves2** [comment]
je viens de réessayer avec la même ligne de commande et ...
youpie tout a fonctionné
mystère

**Comment by simulot** [comment]
Sûrement du à plusieurs facteurs. 
Ravi que cela fonctionne.
