### ISSUE TITLE
Equivalent to --show-path in config file

### ISSUE THREAD

**Issue by LeoDupont** [simulot/aspiratv#62]
Hello

First of all, huge thanks for this incredible work of yours!
I was about to start a very similar project and was amazed to find this gem ;-)

Is there a way to force a show's path when using the config file mode? Similar to the command line argument `--show-path`?

**Comment by simulot** [comment]
Bonjour

Thanks, it's always a pleasure re receive positive feedback.

Sure, I'll add it
