### ISSUE TITLE
automatisation comme HabtiTv

### ISSUE THREAD

**Issue by Mika3578** [simulot/aspiratv#66]
Le code permet il l'automatisation de la surveillance de nouveaux épisodes comme le faisait Habitv? https://github.com/ikfon10/habitv
Merci
Ps: est en projet une interface graphique? web?

**Comment by simulot** [comment]
> Le code permet il l'automatisation de la surveillance de nouveaux épisodes comme le faisait Habitv? https://github.com/ikfon10/habitv

Oui, c'est l'idée. Il y a 2 façons de l'utiliser:
## Avec un fichier de configuration
Le fichier contient les séries / émissions recherchées, et à chaque fois qu'il est lancé, il va faire le tour des recherches et télécharge les nouveautés depuis la dernière éxecution.
Pour l'automatiser, il faut programmer une tâche windows, ou dans cron. 

## A la ligne de commande
Les paramètres permettent de préciser la recherche. Le programme télécharge tous les vidéos pas encore téléchargées.


> Ps: est en projet une interface graphique? web?

J’espère commencer le projet. Mais j'ai besoin d'aide sur la partie front #65
