### ISSUE TITLE
Problem with config.json

### ISSUE THREAD

**Issue by julll190** [simulot/aspiratv#70]
Hi!
I am very happy about the new naming system, I wanted to try it but I had a problem with the config.json file.

I created with the notepad a file "config.json", I copied inside the example you show in the description without modifying it at all.

But when I launch aspiratv (with "aspiratv --config config.json") I get an error message: "[FATAL] [Initialize] Can't decode configuration file: invalid character '}' looking for beginning of object key string"

Do you have an idea of the problem?

Thanks!

**Comment by simulot** [comment]
Sure, the json file is  invalid. Could share it?

**Comment by julll190** [comment]
I just copied your example in an empty file.
Here is the json file : https://we.tl/t-CMm9TNxSeM

In the future, maybe you could add an example of the json file directly in the download package, to help users?

**Comment by simulot** [comment]
Well, the one form the documentation :-(
 I'm Checking.

**Comment by julll190** [comment]
Hi!

Now it works :), thank you very much!

Have a nice day and thank you again to have made this software :)
